sudo: required
language: generic
services:
  - docker

#executed before our tests run
before_install:
  - docker build -t imationschek/docker-react .
 
script:
  - docker run -e CI=true imationschek/docker-react npm run test -- --coverage
#need to make sure that test suite exits at end -> for npm need an extra command for this

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-414651232202"
  # bucket_path: "docker-react2"
  # on: 
  #   branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"