sudo: required
language: generic
services:
  - docker

#executed before our tests run
before_install:
  - docker build -t imationschek/docker-react -f Dockerfile.dev .
 
script:
  - docker run imationschek/docker-react npm run test -- --coverage
#need to make sure that test suite exits at end -> for npm need an extra command for this