FROM node:alpine

WORKDIR '/app'

COPY package.json . 
#copied package.json because of node modules volume - referenced in container
RUN npm install

COPY . . 
#will need this for production code
#can remove copy . . because the app directory is mapped to directory on local machine

RUN ["npm", "run", "start"]

FROM nginx
EXPOSE 80 
#tells Elastic beanstalk which port to expose
COPY --from=0 /app/build usr/share/nginx/html